export default {
    PROVIDER_SHIPPOP : 1,

    //An courier code
    SHIPPOP_COURIER_CODE_FLESH : 1,
    SHIPPOP_COURIER_CODE_KERRY_PICKUP : 2,
    SHIPPOP_COURIER_CODE_SCG : 3,
    SHIPPOP_COURIER_CODE_EMS : 4,
    SHIPPOP_COURIER_CODE_MESSENGER : 101,
}