version: '3.7'

services:
  server:
    container_name: agent-network-server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src/
      - ./nodemon.json:/app/nodemon.json
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run dev
  postgres:
    container_name: agent-network-postgres
    image: postgres:13.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "10000:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: