const ERR_INTERNAL: number = 0;
const SUCCESS: number = 1;
const INPUT_REFERENCE_NO_ALREADY_EXIST = 1001;
const INPUT_PRODUCT_CODE_DOES_NOT_EXIST = 1002;
const INPUT_DES_PHONE_NUMBER_INVALID = 1003;
const INPUT_COD_AMOUNT_INVALID = 1004;
const INPUT_BANK_ACCOUNT_INVALID = 1005;
const INPUT_BANK_INVALID = 1006;
const INPUT_ACCOUNT_NAME_INVALID = 1007;
const INPUT_ACCOUNT_NO_INVALID = 1008;
const INPUT_EMAIL_INVALID = 1009;
const INPUT_FI_CODE_INVALID = 1010;
const INPUT_REFERENCE_NO_INVALID = 1011;
const INPUT_REFERENCE_NO_NOT_EXIST = 1012;

export const Message = {
    [ERR_INTERNAL]: "internal error",
    [SUCCESS]: "success",
    [INPUT_REFERENCE_NO_ALREADY_EXIST]: "referenceNo already exists",
    [INPUT_REFERENCE_NO_INVALID]: "referenceNo invalid",
    [INPUT_REFERENCE_NO_NOT_EXIST]: "referenceNo not exists",
    [INPUT_PRODUCT_CODE_DOES_NOT_EXIST]: "productCode does not exists",
    [INPUT_DES_PHONE_NUMBER_INVALID]: "desPhoneNumber invalid",
    [INPUT_COD_AMOUNT_INVALID]: "codAmount invalid",
    [INPUT_BANK_ACCOUNT_INVALID]: "bankAccount invalid",
    [INPUT_BANK_INVALID]: "bank invalid",
    [INPUT_ACCOUNT_NAME_INVALID]: "accountName invalid",
    [INPUT_ACCOUNT_NO_INVALID]: "accountNo invalid",
    [INPUT_EMAIL_INVALID]: "email invalid",
    [INPUT_FI_CODE_INVALID]: "fiCode invalid",
}

export const HttpStatusCode = {
    [ERR_INTERNAL]: 500,
    [SUCCESS]: 200,
    [INPUT_REFERENCE_NO_ALREADY_EXIST]: 400,
    [INPUT_REFERENCE_NO_INVALID]: 400,
    [INPUT_REFERENCE_NO_NOT_EXIST]: 400,
    [INPUT_PRODUCT_CODE_DOES_NOT_EXIST]: 400,
    [INPUT_DES_PHONE_NUMBER_INVALID]: 400,
    [INPUT_COD_AMOUNT_INVALID]: 400,
    [INPUT_BANK_ACCOUNT_INVALID]: 400,
    [INPUT_BANK_INVALID]: 400,
    [INPUT_ACCOUNT_NAME_INVALID]: 400,
    [INPUT_ACCOUNT_NO_INVALID]: 400,
    [INPUT_EMAIL_INVALID]: 400,
    [INPUT_FI_CODE_INVALID]: 400,
}

export default {
    ERR_INTERNAL,
    SUCCESS,
    INPUT_REFERENCE_NO_ALREADY_EXIST,
    INPUT_REFERENCE_NO_INVALID,
    INPUT_REFERENCE_NO_NOT_EXIST,
    INPUT_PRODUCT_CODE_DOES_NOT_EXIST,
    INPUT_DES_PHONE_NUMBER_INVALID,
    INPUT_COD_AMOUNT_INVALID,
    INPUT_BANK_ACCOUNT_INVALID,
    INPUT_BANK_INVALID,
    INPUT_ACCOUNT_NAME_INVALID,
    INPUT_ACCOUNT_NO_INVALID,
    INPUT_EMAIL_INVALID,
    INPUT_FI_CODE_INVALID,
};