export const POS_SET_TYPE = "POS_SET_TYPE";
export const POS_SET_COURIER_CODE = "POS_SET_COURIER_CODE";
export const POS_SET_COD_AMOUNT = "POS_SET_COD_AMOUNT";
export const POS_SET_DESTINATION = "POS_SET_DESTINATION";
export const POS_SET_AN_ORDER_ID = "POS_SET_AN_ORDER_ID";
export const POS_SET_AN_ORDER_ITEMS = "POS_SET_AN_ORDER_ITEMS";

export const POS_SET_AN_PARCEL = "POS_SET_AN_PARCEL";